stages:
  get_data_from_jira_api:
    desc: >
      This stage will receive data directly from the API and save it to the local storage.
      The data retrieval process does not involve any sensitive information, so the scripts and configurations can be stored in the repository.
      However, sensitive parameters for the API request are stored in the .env, which is added to the .gitignore file.

    cmd: >
      python src/data/get_raw_data_from_jira_api.py
      --output-path data/raw/raw_jira_tasks_from_api.json
    deps:
      - src/.env
    outs:
      - data/raw/raw_jira_tasks_from_api.json
